routes/web.php
<?php

use App\Http\Controllers\Annonceur\AnnonceController;
use App\Http\Controllers\Admin\AnnonceController as AdminController;
use App\Http\Controllers\AuthController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name("home");

//A l'exception de l'affichage de la liste de tous les annonces (méthode index), toutes les routes ne peuvent être accessible que pour les utilisateurs authentifiés
Route::resource("annonce", AnnonceController::class)->except("index")->middleware("auth");
//On définit la route /annonce qui sera accessible par tout le monde (authentifié ou non)
Route::get("annonce", [AnnonceController::class, "index"])->name("annonce.index");


Route::middleware("guest")->group(function(){
    Route::get("register", [AuthController::class, "register"]);
    Route::post("register", [AuthController::class, "registerUser"])->name("register");


    Route::get("login", [AuthController::class, "login"]);
    Route::post("login", [AuthController::class, "loginUser"])->name("login");
});


Route::post("logout", [AuthController::class, "logout"])->name("logout")->middleware("auth");


Route::prefix("admin")->name("admin.")->middleware("auth")->group(function(){
    Route::resource("annonce",AdminController::class );
     Route::delete("changer_etat", [AdminController::class, "changer_etat"])->name("changer_etat");   
});

app/Models/Annonce.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Annonce extends Model
{
    use HasFactory;
    protected $guarded=[];

    public function user(){
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Admin/AnnonceController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\AnnonceRequest;
use App\Models\Annonce;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class AnnonceController extends Controller
{
    
    public function __construct()
    {
        $this->authorizeResource(Annonce::class);
    }
    
    
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        
        $annonces=Annonce::all();
        return view("admin.annonce.index", compact("annonces"));
   
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view("annonce.create");
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(AnnonceRequest $request)
    { 
        $file=$request->photo;
        $path= $file?->store("photos");

        $data=$request->all();

        $data["photo"]=$path;
      
        Annonce::create($data);
        return redirect()->route('annonce.index')->with("success", "L'ajout de la nouvelle annonce a bien réussi!");

    }

    /**
     * Display the specified resource.
     */
    public function show(Annonce $annonce)
    {
        if(isset($annonce))
            return view("annonce.show", compact("annonce"));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Annonce $annonce)
    {
       return view("annonce.edit", compact("annonce"));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(AnnonceRequest $request, Annonce $annonce)
    {
       $file=$request->photo;
        $path= $file?->store("photos");

        $data=$request->all();

        $data["photo"]=$path;
         
        if(isset($annonce->photo))
            Storage::delete($annonce->photo);

        $annonce->update($data);
          return redirect()->route('annonce.index')->with("success", "La modification de l'annonce a bien réussi!");

    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Annonce $annonce)
    {
         if(isset($annonce->photo))
            Storage::delete($annonce->photo);

        $annonce->delete();
        return redirect()->route('annonce.index')->with("success", "La suppression de l'annonce a bien réussi!");

    }

    public function changer_etat(Request $request){
       $this->authorize('changer_etat', App\Models\Annonce::class);

        $etat="en cours";
        if($request->has("valider")){
            $etat="validé";
        }elseif($request->has("signaler")){
            $etat="signalé";
        }

        $ids=$request->ids;
        foreach($ids as $id){
                $annonce=Annonce::find($id);
                // $annonce->etat="validé";
                // $annonce->save();
                $annonce->update(["etat"=>$etat]);
            }

        return redirect()->route("admin.annonce.index")->with("success", "Changement d'état réussi!");
    }
}

app/Http/Controllers/Annonceur/AnnonceController.php
<?php

namespace App\Http\Controllers\Annonceur;

use App\Http\Controllers\Controller;
use App\Http\Requests\AnnonceRequest;
use App\Models\Annonce;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class AnnonceController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        if(Auth::check()){
             $annonces=Annonce::where('etat', 'validé')
                        ->orWhere('user_id', Auth::id())
                        ->get();
        }else{
              $annonces=Annonce::where('etat', 'validé')->get();
        }
      
        return view("annonce.index", compact("annonces"));
   
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $this->authorize('create', App\Models\Annonce::class);
        return view("annonce.create");
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(AnnonceRequest $request)
    { 
         $this->authorize('create', App\Models\Annonce::class);
        $file=$request->photo;
        $path= $file?->store("photos");

        $data=$request->all();

        $data["photo"]=$path;
        $data["user_id"]=Auth::id();
        $data["etat"]="en cours";

        Annonce::create($data);
        return redirect()->route('annonce.index')->with("success", "L'ajout de la nouvelle annonce a bien réussi!");

    }

    /**
     * Display the specified resource.
     */
    public function show(Annonce $annonce)
    {
        if(isset($annonce))
            return view("annonce.show", compact("annonce"));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Annonce $annonce)
    {
        
        $this->authorize('update', $annonce );
        if(isset($annonce))
            return view("annonce.edit", compact("annonce"));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(AnnonceRequest $request, Annonce $annonce)
    {

        $this->authorize('update', $annonce );
       $file=$request->photo;
        $path= $file?->store("photos");

        $data=$request->all();

        $data["photo"]=$path;
        $data["user_id"]=Auth::id();
        $data["etat"]="en cours"; 

        if(isset($annonce->photo))
            Storage::delete($annonce->photo);

        $annonce->update($data);
          return redirect()->route('annonce.index')->with("success", "La modification de l'annonce a bien réussi!");

    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Annonce $annonce)
    {
         $this->authorize('delete', $annonce );
         if(isset($annonce->photo))
            Storage::delete($annonce->photo);

        $annonce->delete();
        return redirect()->route('annonce.index')->with("success", "La suppression de l'annonce a bien réussi!");

    }
}

resources/views/annonce/create.blade.php
@extends("template.master")
@section("titre", "Liste des annonces")
@section("contenu")
<h2 class="mt-2 mb-2">Nouvelle annonce</h2>
@if($errors->any())
    <ul class="alert alert-danger">
        @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
</ul>
@endif
    <form action="{{ route('annonce.store') }}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="mb-3">
        <label for="titre" class="form-label">Titre</label>
        <input type="text" class="form-control" id="titre" name="titre">
        </div>

        <div class="mb-3">
        <label for="description" class="form-label">Description</label>
        <input type="text" class="form-control" id="description" name="description">
        </div>

        <div class="mb-3">
        <label for="type" class="form-label">Type</label>
        <select class="form-select" name="type">
                <option selected>Veuillez choisir un type</option>
                <option value="Appartement">Appartement</option>
                <option value="Maison">Maison</option>
                <option value="Villa">Villa</option>
                <option value="Magasin">Magasin</option>
                <option value="Terrain">Terrain</option>
         </select> </div>

        <div class="mb-3">
        <label for="ville" class="form-label">Ville</label>
        <input type="text" class="form-control" id="ville" name="ville">
        </div>

        <div class="mb-3">
        <label for="superficie" class="form-label">Superficie</label>
        <input type="text" class="form-control" id="superficie" name="superficie">
        </div>

        <div class="mb-3 form-check-inline">
        <label class="form-label ">Etat</label><br>
         <input type="radio" id="neuf" name="neuf" value="1"> Neuf &nbsp;
         <input type="radio" id="neuf" name="neuf"value='0'> Ancien
        </div>

        <div class="mb-3">
        <label for="prix" class="form-label">Prix</label>
        <input type="text" class="form-control" id="prix" name="prix">
        </div>
  <div class="mb-3">
        <label for="photo" class="form-label">Photo</label>
        <input type="file" class="form-control" id="photo" name="photo">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endsection

resources/views/annonce/edit.blade.php
@extends("template.master")
@section("titre", "Liste des annonces")
@section("contenu")
@isset($annonce)
<h2 class="mt-2 mb-2">Modification de l'annonce numero {{ $annonce->id }}</h2>
@if($errors->any())
    <ul class="alert alert-danger">
        @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
</ul>
@endif

    <form action="{{ route('annonce.update', $annonce->id) }}" method="post" enctype="multipart/form-data">
        @csrf
        @method("PUT")
        <div class="mb-3">
        <label for="titre" class="form-label">Titre</label>
        <input type="text" class="form-control" id="titre" name="titre" value="{{$annonce->titre }}"  >
        </div>

        <div class="mb-3">
        <label for="description" class="form-label">Description</label>
        <input type="text" class="form-control" id="description" name="description"  value="{{$annonce->description }}">
        </div>

        <div class="mb-3">
        <label for="type" class="form-label">Type</label>
        <select class="form-select" name="type">
                <option value="Appartement"  {{$annonce->type=="Appartement"? "selected":"" }}  >Appartement</option>
                <option value="Maison" {{$annonce->type=="Maison"? "selected":"" }}>Maison</option>
                <option value="Villa" {{$annonce->type=="Villa"? "selected":"" }}>Villa</option>
                <option value="Magasin" {{$annonce->type=="Magasin"? "selected":"" }} >Magasin</option>
                <option value="Terrain" {{$annonce->type=="Terrain"? "selected":"" }}>Terrain</option>
         </select> </div>

        <div class="mb-3">
        <label for="ville" class="form-label">Ville</label>
        <input type="text" class="form-control" id="ville" name="ville"  value="{{$annonce->ville }}">
        </div>

        <div class="mb-3">
        <label for="superficie" class="form-label">Superficie</label>
        <input type="text" class="form-control" id="superficie" name="superficie"  value="{{$annonce->superficie }}">
        </div>

        <div class="mb-3 form-check-inline">
        <label class="form-label ">Etat</label><br>
         <input type="radio" id="neuf" name="neuf" value="1" {{$annonce->neuf? "checked":"" }}> Neuf &nbsp;
         <input type="radio" id="neuf" name="neuf"value='0' {{$annonce->neuf? "":"checked" }}> Ancien
        </div>

        <div class="mb-3">
        <label for="prix" class="form-label">Prix</label>
        <input type="text" class="form-control" id="prix" name="prix"  value="{{$annonce->prix }}">
        </div>
         <div class="mb-3">
            @isset($annonce->photo)
                <img src="{{ asset($annonce->photo) }}" alt="" width="200px"><br>
             @endisset
        <label for="photo" class="form-label">Photo</label>
        <input type="file" class="form-control" id="photo" name="photo">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endisset
@endsection

resources/views/annonce/index.blade.php
@extends("template.master")
@section("titre", "Liste des annonces")
@section("contenu")

    @isset($annonces)
        <h2 class="mt-3 mb-2">Liste des annonces</h2>
        @if(session()->has("success"))
            <div class="alert alert-success">
                {{session("success")}}
            </div>
        @endif
        @auth
        <a href="{{ route('annonce.create') }}" class="btn btn-primary mb-3">Nouvelle annonce</a>
        @endauth

        <table class="table">
            <tr>
                <th>Photo</th>
                <th>Titre</th>
                <th width="200px">Description</th>
                <th>Type</th>
                <th>Ville</th>
                <th>Superficie(m<sup>2</sup>)</th>
                <th>Etat</th>
                <th>Prix(dhs)</th>
                 @auth  <th>Actions</th> @endauth
            </tr>
            @foreach($annonces as $annonce)
                <tr>
                    <td>
                        @isset($annonce->photo)
                          <img src="{{ asset($annonce->photo) }}" alt="" width="80px">
                        @else
                         <img src="{{ asset('photos/vide.jpg') }}" alt="" width="80px">
                        @endisset
                    </td>
                    <td> <a href="{{ route('annonce.show',$annonce->id) }}" style="color:gray"> {{ $annonce->titre }}</a>
                       </td>
                    <td>{{ $annonce->description }}</td>
                    <td>{{ $annonce->type }}</td>
                    <td>{{ $annonce->ville }}</td>
                    <td>{{ $annonce->superficie }}</td>
                    <td>{{ $annonce->neuf? "Neuf":"Ancien" }}</td>
                    <!-- <td> -->
                        <!-- <input type="checkbox" name="" id="" disabled <?php // $annonce->neuf? "checked":"" ?> }}> -->
                    <!-- </td> -->
                    <td>{{ $annonce->prix }}</td>
                   @auth    
                   <td>
                        @can(['update', 'delete'], $annonce)
                            <form action="{{ route('annonce.destroy',$annonce->id) }}"  method="post">
                                @csrf
                                @method("DELETE")
                            
                                <a href="{{ route('annonce.edit',$annonce->id) }}" style="color:blue"><i class="bi bi-pencil"></i></a>
                                <button type="submit" style="color:red" class="btn border-none"
                                onclick="return confirm('Voulez vous vraiment supprimer l\'annonce : {{$annonce->titre }}?')"
                                ><i class="bi bi-trash2"></i></button>
                            </form>
                            <p class="small"><i>{{$annonce->etat}}</i></p>
                         @endcan
                    </td>
                    @endauth
                </tr>
            @endforeach

        </table>
    @endisset
@endsection

resources/views/annonce/show.blade.php
@extends("template.master")
@section("titre", "Liste des annonces")
@section("contenu")
    @isset($annonce)
        <h2>Détails de l'annonce numéro {{ $annonce->id }}</h2>
        Titre : <b> {{ $annonce->titre }}</b><br>
        Description : <b> {{ $annonce->description }}</b> <br>
        Prix : <b> {{ $annonce->prix }}</b> dhs<br>
        Etat : <b> {{ $annonce->neuf? "Neuf": "Ancien" }}</b>
    @endisset
@endsection